version: '3.4'

services:
  frontend_website_template:
    container_name: frontend_website_template
    build: .
    ports:
      - 1234:1234
    restart: unless-stopped
    tty: true
    volumes:
      # - .:/usr/src/app
      - ./src:/usr/src/app/src
      - ./src/yarn.lock:/usr/src/app/src/yarn.lock