version: '3.4'

services:
  frontend_teacher:
    container_name: frontend_teacher
    build: .
    ports:
      - 1236:1234
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/usr/src/app/src
      - ./src/yarn.lock:/usr/src/app/src/yarn.lock